#
# This file contains configuration flags to customize your site
#

# Name of your site (displayed in the header)
name: 황현동 블로그

# Short bio or description (displayed in the header)
description: 목차

# URL of your avatar or profile pic
avatar: https://avatars2.githubusercontent.com/u/5696570

#
# Flags below are optional
#

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email: h2d2002@naver.com
  facebook:
  flickr:
  github: hyundonghwang
  instagram:
  linkedin:
  pinterest:
  rss: rss
  twitter:
  stackoverflow:
  youtube:
  googleplus:

# Enter your Disqus shortname (not your username) to enable commenting on posts
disqus:

# Enter your Google Analytics web tracking code to activate tracking
google_analytics:

# Your website URL
url: https://hyundonghwang.github.io/

# If you're hosting your site at a Project repository on GitHub pages,
# add the baseurl here, like this: "/repository-name"
baseurl: ""

#
# Custom site settings
#

title: 황현동 블로그
tagline: "개발, 인생, 유우머"
paginate: 20
permalink: pretty

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll only supports Kramdown for Markdown
kramdown:
  input: GFM
  hard_wrap: true
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: "highlight"

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded

# Use the following plug-ins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# About/contact
author:
  name: 황현동
  url: https://avatars2.githubusercontent.com/u/5696570
  email: h2d2002@naver.com

github:
  repo: https://github.com/hyundonghwang

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME
